services:
  syslog:
    build:
      context: '.'
      dockerfile: ./Docker/Dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMATGE_APLICACIO: "debian:bookworm-20260623-slim"
