services:
  alpine:
    image: alpine
    container_name: alpine
    build:
      context: '.'
      dockerfile: ./Docker/dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMAGE_ALPINE: "alpine:latest"
    restart: always
