services:
  mysql5:
    container_name: mysql5
    build:
      context: '.'
      dockerfile: ./Docker/Dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMAGE_MYSQL5: "mysql:5.7.43"
    # volumes:
    #   - db_data:/var/lib/mysql
    #   - ./Docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "4036:3306"
    restart: always
    environment:
      ENVIRONMENT: DEV
      MYSQL_ROOT_PASSWORD: 1nternet!
      MYSQL_DATABASE: sistemes
      MYSQL_USER: sistemes
      MYSQL_PASSWORD: 1nternet!
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
networks:
  apps:
    name: mysql5
volumes:
  db_data: {}
